resolver: lts-22.25
extra-deps:
- emojis-0.1.4.1
ghc-options:
   "$locals": -fhide-source-paths
packages:
- commonmark
- commonmark-extensions
- commonmark-pandoc
- commonmark-cli
# These next two lines are needed to use
# stack build --profile --ghc-options="-fno-prof-auto"
# apply-ghc-options: everything
# rebuild-ghc-options: true
